config/routes.rb
Rails.application.routes.draw do
  devise_for :members, controllers: {
    sessions: 'member/sessions',
    registrations: 'member/sessions'
  }
  devise_for :admins, controllers: {
    sessions: 'admin/sessions',
    registrations: 'admin/sessions'
  }
  devise_for :users
  root 'pages/home#index'
  get 'pages/admin'
  #get 'users/index'
  
  #root "news#index" 
  get 'profile', to: 'users#show'
  resources :news 

  match '/users', to: 'users#index', via: :all 
  match '/users/:id', to: "users#show", via: :get 
  #devise_for :users, :path_prefix => 'd'
  resources :users
  

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  #get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/item.rb
class Item < ApplicationRecord
end

app/models/member.rb
class Member < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/news.rb
class News < ApplicationRecord
end

app/models/user.rb
class User< ApplicationRecord
end

app/controllers/admin/passwords_controller.rb
# frozen_string_literal: true

class Admin::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/admin/sessions_controller.rb
# frozen_string_literal: true

class Admin::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/member/sessions_controller.rb
# frozen_string_literal: true

class Member::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/member/unlocks_controller.rb
# frozen_string_literal: true

class Member::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/member_controller.rb
class MemberController < ApplicationController
end

app/controllers/news_controller.rb
class News < ApplicationController 
  def index 
    @news = news.all 
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def admin
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end
  def show
    @user = User.find_by_id(params[:id])
  end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/member_helper.rb
module MemberHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Guild</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/admin.html.erb
<h1>Pages#admin</h1>
<p>Find me in app/views/pages/admin.html.erb</p>

<div>
<h3>Welcome the the Manticore!</h3>
<h4>Not admin? Please go to guild Membership Portal</h4>
<% if current_admin %>
    <%= link_to "Sign out", destroy_admin_session_path, method: :delete, :data {turbo_method: :delete }%>
    <%= link_to "Edit ", edit_admin_registration_path %>
<% else %>
    <%= link_to "Sign Up", new_admin_registration_path %>
    <%= link_to "Sign In", new_admin_session_path %>
<% end %>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>
<div>
<h3>Welcome the the Manticore!</h3>
<% if current_member %>
    <%= link_to "Sign out", destroy_member_session_path, method: :delete, :data {turbo_method: :delete }%>
    <%= link_to "Edit Membership", edit_member_registration_path %>
<% else %>
    <%= link_to "Sign Up", new_member_registration_path %>
    <%= link_to "Sign In", new_member_session_path %>
<% elsif current_admin %>
    <%= link_to "Sign out", destroy_admin_session_path, method: :delete, :data {turbo_method: :delete }%>
    <%= link_to "Edit ", edit_admin_registration_path %>
<% else %>
    <%= link_to "Sign Up", new_admin_registration_path %>
    <%= link_to "Sign In", new_admin_session_path %>
<% end %>